name: build
on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch: {}
jobs:
  autoupdate:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install zmwangx/npm-noob/noob
    - name: Auto-update npm packages
      run: bash .ci/autoupdate.sh
    - name: Commit changes
      run: |
        git config --local user.email "benjamescunningham@gmail.com"
        git config --local user.name "Ben Cunningham"
        git commit -m "Auto-update formulae" || true
    - name: Push changes to remote
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
