name: tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *
jobs:
  integration:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install formulae
      run: |
        set -eo pipefail
        find Formula -type f | xargs -I path brew install --formula -s path
